server:
  port: 8991

spring:
  application:
    name: MANAGEMENT-SERVICE
  security:
    user:
      password: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddemo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/