#端口
server:
  port: 8776
##ssl
#  ssl:
#    enabled: true
#    key-store: classpath:client1.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: client1

spring:
  application:
    name: gateway-service
#redis连接
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
    timeout: 3000

#配置spring session采用redis
  session:
    store-type: redis
  cloud:
    gateway:
      #https
#      httpclient:
#        ssl:
#          useInsecureTrustManager: true
      globalcors:
        #跨域
        cors-configurations:
          '[/**]' :
            # 允许携带认证信息
            allow-credentials: true
            # 允许跨域请求里的head字段，设置*为全部
            allowed-origins: "*"
            # 允许跨域的源(网站域名/ip)，设置*为全部
            allowed-headers: "*"
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            # 跨域允许的有效期
            max-age: 3600
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        #转发服务配置
        #管理
        - id: management-service
          uri: lb://MANAGEMENT-SERVICE
          predicates:
            - Path=/api/management/**
          filters:
#            - StripPrefix=1
            - RequestTime=true
        #用户
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
          filters:
#            - StripPrefix=1
            - RequestTime=true
            - UserGlobalFilter

            #信息评估
        - id: rating-service
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/prodrating/**
          filters:
#            - StripPrefix=1
            - RequestTime=true

            #风控评估
        - id: market-service
          uri: lb://MARKET-SERVICE
          predicates:
            - Path=/api/market/**
          filters:
            - RequestTime=true

#注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




